version: "3.8"

networks:
  dev:
    driver: bridge

services:
  todoapi:
    image: todoapi
    depends_on:
      - "app_db"
    container_name: todoapi-services
    ports:
      - "5151:80"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
     - ConnectionStrings_DbConnection=User ID=postgres;Password=J0ulupukk!;Server=localhost;Port=5433;Database=tododb;IntegratedSecurity=true;Pooling=true;
     - ASPNETCORE_URLS=http://+:80
    networks:
     - dev 

  app_db:
    image: postgres:latest
    container_name: app_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tododb
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
    - dev

volumes:
  app_data:
